language_dict = {
    'ru': 'Russian',
    'fa': 'Persian',
    'it': 'Italian',
    'tr': 'Turkish',
    'et': 'Estonian',
    'hu': 'Hungarian',
    'de': 'German',
    'el': 'Greek',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'te': 'Telugu',
    'eu': 'Basque',
    'sl': 'Slovenian',
    'da': 'Danish',
    'en': 'English',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'hi': 'Hindi',
    'is': 'Icelandic',
    'bn': 'Bengali',
    'in': 'Indonesian',
    'kn': 'Kannada',
    'ko': 'Korean',
    'nd': 'North Ndebele',
    'no': 'Norwegian',
    'sv': 'Swedish',
    'lv': 'Latvian',
    'ht': 'Haitian Creole',
    'ta': 'Tamil',
    'es': 'Spanish',
    'fr': 'French',
    'nl': 'Dutch',
    'pl': 'Polish',
    'mr': 'Marathi',
    'fi': 'Finnish',
    'ur': 'Urdu',
    'tl': 'Tagalog',
    'ja': 'Japanese',
    'iw': 'Hebrew',
    'cy': 'Welsh',
    'uk': 'Ukrainian',
    'ar': 'Arabic',
    'cs': 'Czech',
    'zh': 'Chinese',
    'ca': 'Catalan'
}
